name: "Deploy"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  Deploy-Contracts:
    name: Deploy-Contracts
    runs-on: ubuntu-latest
    steps:
      #Check out
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: onfinality
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: arm64,amd64
          file: ./Dockerfile
          tags: onfinality/indexer-ssl-proxy:rev-${{steps.vars.outputs.sha_short}},onfinality/indexer-ssl-proxy:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
